model: 
    input_path: "model"
    output_name: "output"
    v2: true #今のところ使わないのだが、一応
    v_prediction: false #SDv2(768)系のみtrue
    sdxl: true
    clip_skip: -2
    
dataset:
    module: utils.dataset.BaseDataset
    args:
        metadata: "buckets.json"
        path: "dataset"
        latents: "latents"
        mask: false
        pfg: false
        control: false
    loader:
        module: torch.utils.data.DataLoader
        collate_fn: "identity"
        args:
            num_workers: 8
save:
    module: utils.save.Save
    args:
        wandb_name: "sd-trainer"
        over_write: true
        save_n_epochs: 1
        save_n_steps: 100
        image_logs: null
        num_images: 4
        resolution: "640,896"
        prompt: null
        negative_prompt: "worst quality, low quality, medium quality, deleted, lowres, comic, bad anatomy,bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, signature, watermark, username, blurry"
        seed: 4545
        
train:
    train_unet: false
    train_encoder: false
    lr: "1e-3"
    lr_scheduler: "cosine"
    epochs: 10
    batch_size: 8
    amp: "bfloat16"
    gradient_checkpointing: false
    use_xformers: true

feature:
    minibatch_repeat: 1
    up_only: false
    step_range: "0.0,1.0"
    test_steps: -1
    
optimizer:
    module: torch.optim.AdamW
    #args: 引数も指定できます。

network:
    module: networks.lora.LoRANetwork
    train: true
    resume: null
    args:
        rank: 16 # "dynamic"で動的に決定
        conv_rank: 16 # 指定するとloconになる
        module: null # "loha"でlohaになる